<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>ProjectOracle.AcceptanceTests</AssemblyName>
    <RootNamespace>ProjectOracle.AcceptanceTests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/ProjectOracle.Core/ProjectOracle.Core.csproj" />
    <ProjectReference Include="../../src/ProjectOracle.Console/ProjectOracle.Console.csproj" />
  </ItemGroup>
</Project>
