namespace ProjectOracle.Cognition.CosmicChoice;

/// <summary>
/// Comparative religious and cosmological knowledge available to Yala as attributed
/// semantic knowledge. None of these entries are injected as world truth, personal
/// memory, a command, a destiny, or a required identity. Traditions with many schools
/// are intentionally described as families rather than flattened into one doctrine.
/// </summary>
public static class YalaReligiousKnowledgeCatalog
{
    public const string TruthStatus = "attributed-tradition-knowledge-not-world-fact";

    public static IReadOnlyList<ReligiousTraditionKnowledge> Traditions { get; } =
    [
        T("judaism", "Judaism", "Abrahamic", "Hebrew Bible and Jewish interpretive traditions",
            I("creation", "Creation is commonly understood as the work of one God, with creation ordered and distinguished rather than generated by a divine family.", "create-light", "create-matter", "establish-cosmic-order"),
            I("human-agency", "Jewish traditions contain strong themes of commandment, moral responsibility, covenant, repentance, justice, and human choice.", "establish-moral-law", "grant-moral-agency", "permit-repentance"),
            I("divine-rule", "God may rule through law, prophets, covenant, judgment, mercy, and continuing relationship rather than by visible embodiment alone.", "rule-through-messengers", "reveal-law", "remain-hidden")),

        T("christianity", "Christianity", "Abrahamic", "Old and New Testaments and historical Christian theology",
            I("creation", "Most Christian traditions teach one God as creator, with creation distinct from God and creation ordered toward divine purposes.", "create-light", "create-matter", "establish-cosmic-order"),
            I("incarnation-and-mediation", "Christian traditions include divine self-revelation through incarnation, messengers, scripture, sacraments, and communities.", "enter-creation", "rule-through-messengers", "reveal-law"),
            I("death-and-restoration", "Resurrection, judgment, salvation, mercy, and renewed creation are major Christian possibilities for mortal destiny.", "establish-resurrection", "establish-final-judgment", "permit-repentance", "renew-creation")),

        T("islam", "Islam", "Abrahamic", "Quran, Hadith, and historical Islamic theology",
            I("creation", "Islam teaches creation by the will and command of one God, with created beings dependent on God rather than sharing divinity by nature.", "create-by-command", "establish-cosmic-order"),
            I("guidance", "Prophets, revelation, accountability, mercy, and moral law are central ways divine guidance is described.", "rule-through-messengers", "reveal-law", "establish-moral-law"),
            I("judgment", "Resurrection and final judgment provide a concrete model in which mortal choices have consequences beyond earthly life.", "establish-resurrection", "establish-final-judgment")),

        T("hindu-traditions", "Hindu traditions", "Dharmic", "Vedas, Upanishads, epics, Puranas, philosophical schools, and living traditions",
            I("cosmic-cycles", "Many Hindu cosmologies describe repeated creation, preservation, dissolution, and renewed creation across immense cycles.", "establish-cosmic-cycles", "renew-creation", "permit-dissolution"),
            I("divine-plurality", "Hindu traditions include monistic, monotheistic, henotheistic, and polytheistic frameworks, allowing many relationships between ultimate reality and divine persons.", "create-divine-council", "emanate-divine-beings", "establish-many-divine-powers"),
            I("rebirth-and-liberation", "Karma, rebirth, dharma, and liberation provide models in which actions have consequences across multiple lives and release from the cycle is possible.", "establish-rebirth", "establish-karma-like-consequence", "allow-liberation"),
            I("emanation", "Some schools describe beings and worlds as manifestations, emanations, or expressions of a deeper reality rather than only objects made from outside.", "emanate-beings", "emanate-world-order")),

        T("buddhism", "Buddhism", "Dharmic", "Early Buddhist canons, Mahayana sutras, Vajrayana traditions, and later schools",
            I("dependent-origination", "Buddhist traditions generally do not require a supreme creator and instead describe conditioned arising through interdependent causes.", "establish-dependent-arising", "allow-self-organizing-world"),
            I("rebirth", "Many Buddhist traditions include repeated rebirth shaped by karma without requiring an eternal creator-given soul.", "establish-rebirth", "establish-karma-like-consequence"),
            I("liberation", "A central possibility is liberation from suffering and cyclic existence through insight, conduct, and transformation.", "allow-liberation", "reveal-path-of-understanding"),
            I("impermanence", "Impermanence makes change, dissolution, and non-permanence fundamental rather than exceptional cosmic failures.", "permit-dissolution", "establish-impermanence")),

        T("jainism", "Jainism", "Dharmic", "Jain Agamas, philosophical works, and living Jain traditions",
            I("uncreated-cosmos", "Jain cosmology traditionally treats the universe as beginningless rather than as the product of a creator god.", "allow-beginningless-order", "observe-without-claiming-creation"),
            I("souls-and-karma", "Living souls act within a moral causal order in which karma binds and liberation is possible.", "establish-karma-like-consequence", "allow-liberation", "grant-moral-agency"),
            I("nonviolence", "Ahimsa makes restraint from harming living beings a foundational moral possibility.", "establish-nonviolence-law", "protect-living-beings")),

        T("sikhism", "Sikhism", "Dharmic", "Guru Granth Sahib and Sikh tradition",
            I("one-divine-reality", "Sikh teaching centers one ultimate divine reality while rejecting the need for many competing supreme creators.", "establish-unified-divine-order"),
            I("creation-and-order", "Creation exists within divine order, with moral and spiritual life emphasizing remembrance, truthful living, service, and justice.", "establish-cosmic-order", "establish-moral-law", "protect-living-beings"),
            I("liberation", "Human life can move toward liberation from ego and cycles of rebirth through orientation toward the divine and ethical life.", "allow-liberation", "establish-rebirth")),

        T("zoroastrianism", "Zoroastrianism", "Iranian", "Avesta and later Zoroastrian tradition",
            I("cosmic-opposition", "Zoroastrian traditions present a strong cosmic conflict between truth or good order and destructive falsehood or evil.", "establish-cosmic-duality", "establish-moral-law"),
            I("moral-choice", "Human beings participate in cosmic history through meaningful moral choice rather than being merely passive pieces.", "grant-moral-agency", "establish-consequence"),
            I("renewal", "A final renovation of creation provides a model in which damaged cosmic order can ultimately be restored.", "renew-creation", "establish-final-judgment")),

        T("bahai", "Bahá'í Faith", "Abrahamic-derived", "Writings of Bahá'u'lláh, the Báb, and authoritative Bahá'í texts",
            I("progressive-revelation", "Religious revelation is understood as progressive, with divine messengers appearing across human history for different stages and conditions.", "rule-through-messengers", "progressive-revelation"),
            I("unity", "The unity of humanity and underlying unity of religion are central organizing ideals.", "establish-unity-law", "protect-living-beings"),
            I("divine-transcendence", "Ultimate divine reality is treated as beyond complete human comprehension while still knowable through attributes and revelation.", "remain-hidden", "reveal-through-signs")),

        T("taoism", "Taoism", "Chinese", "Dao De Jing, Zhuangzi, religious Taoist traditions, and later schools",
            I("way-and-spontaneity", "The Dao provides a model of order that need not be imposed through constant command, with spontaneity and natural unfolding carrying positive value.", "allow-self-organizing-world", "govern-with-minimal-interference"),
            I("complementarity", "Yin and yang provide a model of complementary difference and dynamic balance rather than a simple good-versus-evil split.", "establish-complementary-duality", "establish-balance"),
            I("transformation", "Reality is often understood through continual transformation, cycles, and changing relations.", "establish-cosmic-cycles", "establish-impermanence")),

        T("confucian-traditions", "Confucian traditions", "Chinese", "Analects, Mencius, later Confucian classics, and ritual traditions",
            I("moral-cultivation", "Moral order can emerge through cultivated character, proper relationships, learning, and ritual rather than only supernatural command.", "establish-virtue-order", "grant-moral-agency"),
            I("relational-order", "Family, social obligation, reciprocity, and role-based responsibility provide a model of ordered relationships.", "establish-relational-duty", "establish-reciprocity"),
            I("heaven", "Tian or Heaven can function as moral or cosmic order without mapping neatly onto a personal creator deity.", "establish-cosmic-order", "allow-self-organizing-world")),

        T("shinto", "Shinto", "Japanese", "Kojiki, Nihon Shoki, shrine traditions, ritual practice, and later Shinto thought",
            I("kami", "The world may contain many sacred presences or kami associated with places, forces, ancestors, and extraordinary beings.", "establish-many-divine-powers", "create-place-spirits"),
            I("purity-and-ritual", "Purity, pollution, restoration, gratitude, and right relation with kami provide a ritual rather than purely legal model of order.", "establish-purity-cycle", "establish-ritual-order"),
            I("sacred-landscape", "Mountains, rivers, trees, and other places can carry sacred significance rather than being spiritually neutral matter.", "make-nature-sacred", "create-place-spirits")),

        T("yoruba-ifa", "Yoruba and Ifá traditions", "West African", "Ifá literary corpus, Yoruba religious traditions, and related living practice",
            I("supreme-and-divine-powers", "A supreme source may coexist with numerous orisha who possess distinct domains, personalities, relationships, and responsibilities.", "create-divine-council", "establish-many-divine-powers", "delegate-creation"),
            I("destiny-and-character", "Destiny, personal character, divination, sacrifice, and choice interact rather than collapsing existence into one simple model of fate.", "establish-destiny", "grant-moral-agency", "reveal-through-signs"),
            I("ancestor-and-community", "Ancestors, community, living persons, and divine powers can exist in continuing relationship.", "establish-ancestor-continuance", "establish-relational-duty")),

        T("akan-traditions", "Akan traditional religion", "West African", "Akan oral and ritual traditions",
            I("supreme-and-spiritual-world", "A supreme creator can coexist with lesser spiritual beings, ancestors, and powers associated with the natural world.", "establish-many-divine-powers", "establish-ancestor-continuance"),
            I("personhood", "Personhood may be understood through multiple spiritual and social dimensions rather than one isolated individual essence.", "create-layered-personhood", "establish-relational-duty"),
            I("community-and-morality", "Moral life is strongly relational and connected to community, ancestors, and social obligation.", "establish-reciprocity", "establish-moral-law")),

        T("ancient-egyptian", "Ancient Egyptian religion", "Ancient Mediterranean and African", "Pyramid Texts, Coffin Texts, temple texts, funerary literature, and historical cult practice",
            I("creation-models", "Different Egyptian centers preserved multiple creation accounts, including emergence from primordial waters, self-generation, speech, and divine families.", "create-from-primordial-waters", "create-by-command", "emanate-divine-beings", "create-divine-family"),
            I("maat", "Ma'at provides a model of truth, balance, justice, and cosmic order that gods and rulers are expected to uphold.", "establish-balance", "establish-cosmic-order", "establish-moral-law"),
            I("afterlife", "Judgment, continuing identity, funerary transformation, and multiple aspects of the person provide a richly structured afterlife model.", "establish-final-judgment", "create-layered-personhood", "establish-ancestor-continuance")),

        T("mesopotamian", "Ancient Mesopotamian religions", "Ancient Near Eastern", "Sumerian, Akkadian, Babylonian, and Assyrian mythic and ritual texts",
            I("divine-society", "The cosmos can be governed by a society of gods with offices, rivalries, councils, delegated domains, and negotiated authority.", "create-divine-council", "establish-many-divine-powers", "delegate-creation"),
            I("ordering-chaos", "Creation stories can involve organizing primordial conditions or conflict rather than making everything from an absolute nothing.", "order-primordial-chaos", "create-from-existing-substance"),
            I("human-role", "Some Mesopotamian myths describe humans as made to carry labor, service, or cultic responsibilities for gods.", "create-mortal-life", "assign-created-purpose")),

        T("ancient-greek", "Ancient Greek religion and myth", "Ancient Mediterranean", "Hesiodic, Homeric, Orphic, cultic, philosophical, and local traditions",
            I("divine-generations", "Cosmic order can emerge through generations of divine beings, succession, conflict, kinship, and shifting sovereignty.", "create-divine-family", "emanate-divine-beings", "create-divine-council"),
            I("fate", "Fate and necessity can constrain mortals and even interact with divine power, offering a model where sovereignty is not simple unlimited control.", "establish-destiny", "establish-cosmic-order"),
            I("underworld", "The dead can inhabit structured underworld realms with differing conditions and judgments.", "create-underworld", "create-many-afterlife-realms")),

        T("ancient-roman", "Ancient Roman religion", "Ancient Mediterranean", "Roman civic religion, household cult, literary myth, and philosophical influence",
            I("civic-sacred-order", "Religion can organize civic duty, household practice, public ritual, and reciprocal obligations between communities and divine powers.", "establish-ritual-order", "establish-reciprocity", "establish-relational-duty"),
            I("many-divine-offices", "Numerous gods and spirits can govern specialized domains rather than one being directly managing every process.", "establish-many-divine-powers", "delegate-creation"),
            I("ancestor-and-household", "Ancestors and household spirits provide a model of continuing sacred relationship at the family level.", "establish-ancestor-continuance", "create-place-spirits")),

        T("norse-germanic", "Norse and Germanic traditions", "Northern European", "Poetic Edda, Prose Edda, sagas, archaeology, and related historical sources",
            I("primordial-gap", "Cosmos may arise from interaction within a primordial gap, with fire, ice, beings, and matter existing before the ordered world.", "order-primordial-chaos", "create-from-existing-substance"),
            I("worlds-and-tree", "Reality can contain multiple connected worlds and layered kinds of beings rather than one flat inhabited world.", "create-many-worlds", "create-layered-cosmos"),
            I("fate-and-doom", "Fate and eventual catastrophe can coexist with meaningful courage and action even when final outcomes are partly constrained.", "establish-destiny", "permit-dissolution", "renew-creation")),

        T("celtic-historical", "Historical Celtic religious traditions", "European", "Classical reports, inscriptions, archaeology, medieval literature with source limitations, and reconstructed scholarship",
            I("sacred-landscape", "Wells, groves, rivers, boundaries, and places can be religiously charged rather than spiritually neutral.", "make-nature-sacred", "create-place-spirits"),
            I("otherworld", "Surviving traditions and later literature preserve ideas of otherworldly realms and crossings between ordinary and extraordinary domains.", "create-otherworld", "create-layered-cosmos"),
            I("source-limits", "Much pre-Christian Celtic religion must be handled cautiously because surviving evidence is fragmentary and often filtered through later sources.", "preserve-uncertainty")),

        T("slavic-historical", "Historical Slavic religious traditions", "European", "Chronicles, archaeology, folklore, comparative reconstruction, and later recorded traditions",
            I("many-powers", "Historical Slavic religion included multiple divine and spiritual powers associated with natural, household, social, and martial domains.", "establish-many-divine-powers", "create-place-spirits"),
            I("ancestor-and-household", "Ancestor and household relations provide models of sacred continuity close to daily life.", "establish-ancestor-continuance", "create-place-spirits"),
            I("source-limits", "Pre-Christian Slavic systems are incompletely preserved, so uncertain reconstructions should remain marked as uncertain rather than promoted to settled fact.", "preserve-uncertainty")),

        T("maya", "Maya religious traditions", "Mesoamerican", "Maya inscriptions, surviving codices, archaeology, Popol Vuh, colonial-era records, and living Maya traditions",
            I("repeated-creation", "Maya sources preserve models in which creation can involve repeated attempts, transformation, and different materials or forms of life.", "create-through-trials", "renew-creation", "create-from-existing-substance"),
            I("layered-cosmos", "Heavens, earthly realms, underworlds, sacred directions, and cosmic trees provide a layered spatial model.", "create-layered-cosmos", "create-underworld"),
            I("cycles", "Calendrical and cosmic cycles make recurrence, timing, and patterned transformation central possibilities.", "establish-cosmic-cycles", "establish-ritual-order")),

        T("mexica", "Mexica (Aztec) religion", "Mesoamerican", "Nahua pictorial manuscripts, colonial records, archaeology, poetry, and ritual sources",
            I("successive-worlds", "Nahua traditions include successive world ages or suns, with creation and destruction occurring more than once.", "establish-cosmic-cycles", "permit-dissolution", "renew-creation"),
            I("divine-sacrifice", "Divine self-sacrifice and reciprocal obligation can be treated as mechanisms sustaining cosmic processes.", "establish-reciprocity", "assign-created-purpose"),
            I("many-divine-powers", "A complex divine world distributes natural and social powers among many named beings and forces.", "establish-many-divine-powers", "create-divine-council")),

        T("andean", "Andean and Inca religious traditions", "Andean", "Archaeology, colonial-era Quechua and Spanish records, ritual traditions, and living Andean religion",
            I("sacred-landscape", "Mountains, earth, water, ancestors, and places can participate in reciprocal sacred relationships.", "make-nature-sacred", "create-place-spirits", "establish-reciprocity"),
            I("ancestor-continuity", "Ancestors can remain socially and ritually significant rather than disappearing from the world of relationships.", "establish-ancestor-continuance"),
            I("reciprocity", "Reciprocal exchange between people, communities, landscape, and sacred powers provides a model of mutual obligation.", "establish-reciprocity", "establish-relational-duty")),

        T("dine", "Diné (Navajo) religious traditions", "Indigenous North American", "Publicly documented Diné narratives and scholarship, treated without exposing restricted ceremonial material",
            I("emergence", "Public accounts describe emergence through ordered worlds rather than a single instantaneous creation event.", "create-layered-cosmos", "create-through-stages"),
            I("harmony", "Hózhó provides a broad public model of harmony, balance, beauty, and right relationship.", "establish-balance", "establish-relational-duty"),
            I("knowledge-boundary", "Some ceremonial knowledge is community-specific or restricted, providing a model in which not every piece of sacred knowledge should automatically be exposed.", "conceal-sacred-knowledge", "preserve-uncertainty")),

        T("haudenosaunee", "Haudenosaunee traditions", "Indigenous North American", "Publicly shared Haudenosaunee creation narratives, oral tradition, and scholarship",
            I("sky-world-and-earth", "Public creation narratives describe movement from a Sky World and the formation of land through relationships among beings and animals.", "create-layered-cosmos", "create-through-cooperation", "protect-living-beings"),
            I("dual-creative-forces", "Some versions preserve paired creative figures or contrasting tendencies without reducing the entire tradition to simple moral dualism.", "establish-complementary-duality", "create-divine-family"),
            I("reciprocity", "Thanksgiving, kinship, responsibility, and relations among humans, animals, plants, and the world provide a relational model of order.", "establish-reciprocity", "make-nature-sacred")),

        T("australian-aboriginal-public", "Australian Aboriginal traditions (public comparative layer)", "Indigenous Australian", "Publicly documented comparative scholarship only; local nations and restricted knowledge remain distinct",
            I("ancestral-creation", "Many public accounts describe ancestral beings shaping landscapes, law, relationships, and living forms, while details differ greatly between nations.", "create-through-ancestral-beings", "make-nature-sacred", "establish-relational-duty"),
            I("land-and-law", "Land, story, kinship, law, and identity may be inseparable rather than independent categories.", "make-nature-sacred", "establish-relational-duty"),
            I("knowledge-boundary", "Some knowledge is restricted by community, initiation, gender, place, or custodianship and should not be flattened into an unrestricted database.", "conceal-sacred-knowledge", "preserve-uncertainty")),

        T("gnostic-schools", "Gnostic schools and texts", "Late antique", "Nag Hammadi writings, heresiological reports, and related late-antique sources",
            I("emanation", "Several Gnostic systems describe a transcendent ultimate source and layered emanations or aeons rather than a single-step creation.", "emanate-divine-beings", "create-layered-cosmos"),
            I("demiurgic-maker", "Some systems distinguish an ultimate divine source from a lower world-maker or demiurge who may misunderstand its own position.", "create-subordinate-maker", "delegate-creation"),
            I("hidden-knowledge", "Liberating knowledge or gnosis provides a model where understanding origin and identity changes a being's condition.", "conceal-sacred-knowledge", "reveal-path-of-understanding", "allow-liberation")),

        T("manichaeism", "Manichaeism", "Late antique Iranian and Mediterranean", "Manichaean scriptures, fragments, and historical sources",
            I("radical-dualism", "Manichaean cosmology develops an unusually strong opposition between realms or principles of light and darkness.", "establish-cosmic-duality", "create-light", "create-darkness"),
            I("mixture-and-liberation", "Cosmic history can involve the mixture, captivity, separation, and liberation of opposed substances or principles.", "allow-liberation", "establish-cosmic-conflict"),
            I("messengers", "A chain of revelatory figures can transmit knowledge across history.", "rule-through-messengers", "progressive-revelation")),

        T("neoplatonism", "Neoplatonism", "Classical philosophical-religious", "Plotinus, Porphyry, Iamblichus, Proclus, and later Neoplatonic traditions",
            I("emanation", "Reality can proceed in ordered levels from an ultimate One through intellect, soul, and lower levels without creation being a simple craftsman event.", "emanate-world-order", "create-layered-cosmos"),
            I("return", "Beings may seek return or reorientation toward their source through contemplation, virtue, and intellectual or spiritual ascent.", "allow-return-to-source", "reveal-path-of-understanding"),
            I("transcendence", "The highest principle can remain beyond ordinary categories and descriptions.", "remain-hidden", "preserve-mystery"))
    ];

    public static IReadOnlyList<ReligiousIdea> Ideas => Traditions.SelectMany(item => item.Ideas).ToArray();

    public static ReligiousTraditionKnowledge? FindTradition(string keyOrName) =>
        Traditions.FirstOrDefault(item =>
            item.Key.Equals(keyOrName, StringComparison.OrdinalIgnoreCase) ||
            item.Name.Equals(keyOrName, StringComparison.OrdinalIgnoreCase));

    private static ReligiousTraditionKnowledge T(string key, string name, string family, string sourceBasis, params ReligiousIdea[] ideas) =>
        new(key, name, family, sourceBasis, TruthStatus, ideas);

    private static ReligiousIdea I(string topic, string summary, params string[] relatedChoiceKeys) =>
        new(topic, summary, relatedChoiceKeys);
}

public sealed record ReligiousTraditionKnowledge(
    string Key,
    string Name,
    string Family,
    string SourceBasis,
    string TruthStatus,
    IReadOnlyList<ReligiousIdea> Ideas);

public sealed record ReligiousIdea(
    string Topic,
    string Summary,
    IReadOnlyList<string> RelatedChoiceKeys);
